import 'models/tweet_model.dart';

List<TweetModel> posts = [
  TweetModel(
      userImage: "assets/icons/golib.jpg",
      userName: "☬͜͜ ͜͡➣͜͡ ͜͡☬͜͡🅖͜͡ʻ🅞͜͡🅛͜͡🅘͜͡🅑͜͡☬͜͜ ͜͡➣͜͡ ͜͡☬",
      nickName: "@QADRIMGA_YET_TUPOY",
      tweetTime: "12h",
      textContent: "Bolla hammaga salom",
      commentNumber: 28,
      retweetNumber: 5,
      likeNumber: 21,
      actionType: " liked",
      actionIcon: "assets/icons/heart.svg",
      actionUserNameList: ["Kieron Dotson", "Zack John"]),
  TweetModel(
      userImage: "assets/icons/Asatbek.jpg",
      userName: "Asatbek",
      nickName: "@k_e_b_d_a_s_A",
      tweetTime: "3h",
      textContent: "Dars 4etajda bolayapti bolar \nkellilar",
      commentNumber: 46,
      retweetNumber: 18,
      likeNumber: 363,
      actionType: " liked",
      actionIcon: "assets/icons/heart.svg",
      actionUserNameList: ["Zack John"]),
  TweetModel(
      userImage: "assets/icons/Abror.jpg",
      userName: "Abror Abdulboriyev",
      isOfficialAccount: true,
      nickName: "@SpaceX16o9",
      tweetTime: "14h",
      textContent: "Bugun Boraman Uqishga",
      commentNumber: 7,
      retweetNumber: 1,
      likeNumber: 11,
      actionType: " Retweeted",
      actionIcon: "assets/icons/comment.svg",
      actionUserNameList: ["Kieron Dotson"]),
  TweetModel(
      userImage: "assets/icons/aa.jpg",
      userName: "Abdujabbor",
      nickName: "@Elvish",
      tweetTime: "10h",
      textContent: "Salom hammaga Uy vazifalar qilindimi 🙌",
      contentImage: "assets/icons/aa.jpg",
      commentNumber: 7,
      retweetNumber: 1,
      likeNumber: 11,
      actionType: " Retweeted",
      actionIcon: "assets/icons/comment.svg",
      actionUserNameList: ["Kieron Dotson"]),
];
